### ISSUE TITLE
[DEPLOY] 배포 환경에 Redis 추가

### ISSUE THREAD

**Issue by mingulmangul** [TEAM-DHS/dhs-server#11]
## 📣 Description

배포 환경에 Redis 설정을 추가합니다.

## ✅ TODO

- [x] docker compose 수정
- [x] deploy workflow 수정
- [x] 스프링 애플리케이션 설정 수정
