### ISSUE TITLE
[FEAT] 행사 등록 API

### ISSUE THREAD

**Issue by mingulmangul** [TEAM-DHS/dhs-server#24]
## 📣 Description

행사 등록 API를 개발합니다.

## ✅ TODO

- [x] 컨트롤러 메소드 추가
- [x] 서비스 메소드 추가
- [x] 요청/응답 형식 구성
