### ISSUE TITLE
[FEAT] 행사 참가 신청 API

### ISSUE THREAD

**Issue by mingulmangul** [TEAM-DHS/dhs-server#27]
## 📣 Description

행사 참가 신청 API를 개발합니다.

## ✅ TODO

- [ ] 컨트롤러 메소드 추가
- [ ] 서비스 메소드 추가
- [ ] 요청/응답 형식 구성
