### ISSUE TITLE
[FEAT] 행사 좋아요 API

### ISSUE THREAD

**Issue by mingulmangul** [TEAM-DHS/dhs-server#29]
## 📣 Description

행사에 좋아요를 등록/삭제하는 API를 개발합니다.

## ✅ TODO

- [x] 요청/응답 DTO 생성
- [x] 컨트롤러 메소드 추가
- [x] 서비스 메소드 추가
