### ISSUE TITLE
[FEAT] 좋아요한 행사 리스트 조회 API

### ISSUE THREAD

**Issue by mingulmangul** [TEAM-DHS/dhs-server#31]
## 📣 Description

좋아요한 행사 리스트를 조회하는 API를 개발합니다.

## ✅ TODO

- [x] 요청/응답 DTO 생성
- [x] 컨트롤러 메소드 추가
- [x] 서비스 메소드 추가
- [x] 쿼리 작성
