### ISSUE TITLE
[FEAT] 행사 참가 신청

### ISSUE THREAD

**Issue by mingulmangul** [TEAM-DHS/dhs-server#44]
## 📣 Description

행사 참가 신청 시 행사의 registrationNumber가 증가하도록 수정하고,
신청한 행사 리스트에 신청 정보를 포함하도록 수정하고,
신청 정보의 개별 조회 API와 신청 정보 수정 API를 개발합니다.

## ✅ TODO

- [x] 참사 신청 생성 로직 수정
- [x] 신청한 행사 리스트에 신청 정보를 포함
- [x] 신청 정보 조회 API 개발
- [x] 신청 정보 수정 API 개발
